parameters:
    database_driver:   pdo_sqlite
    database_name:     sunshinephp
    database_path:     %kernel.root_dir%/data/sunshine.db3

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            $un$hine
